# Generated by Django 6.0.5 on 2026-05-08 11:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentWebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(max_length=50)),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('processed', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payment_webhook_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('subscription', 'Subscription Payment'), ('withdrawal', 'Withdrawal Payment'), ('deposit', 'Deposit'), ('refund', 'Refund')], max_length=20)),
                ('payment_method', models.CharField(choices=[('binance', 'Binance Pay'), ('okx', 'OKX Pay'), ('paypal', 'PayPal'), ('mpesa', 'M-Pesa'), ('bank', 'Bank Transfer'), ('card', 'Credit/Debit Card')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('crypto_amount', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('crypto_currency', models.CharField(blank=True, max_length=10)),
                ('crypto_address', models.CharField(blank=True, max_length=255)),
                ('crypto_tx_hash', models.CharField(blank=True, max_length=255)),
                ('transaction_id', models.CharField(blank=True, max_length=255, unique=True)),
                ('gateway_transaction_id', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('webhook_payload', models.JSONField(blank=True, default=dict)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_transactions',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='payment_tra_user_id_131e27_idx'), models.Index(fields=['transaction_id'], name='payment_tra_transac_4a22d3_idx'), models.Index(fields=['payment_type', 'status'], name='payment_tra_payment_aacde6_idx')],
            },
        ),
    ]
