# Generated by Django 6.0.5 on 2026-05-08 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('project_brief', models.TextField(help_text='The project applicant must complete before interview')),
                ('salary_range', models.CharField(max_length=100)),
                ('location', models.CharField(default='Remote', max_length=255)),
                ('job_type', models.CharField(choices=[('freelance', 'Freelance'), ('fulltime', 'Full Time'), ('parttime', 'Part Time')], default='freelance', max_length=20)),
                ('experience_level', models.CharField(choices=[('entry', 'Entry Level'), ('intermediate', 'Intermediate'), ('senior', 'Senior'), ('expert', 'Expert')], default='intermediate', max_length=20)),
                ('skills_required', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active', '-created_at'], name='jobs_is_acti_720973_idx'), models.Index(fields=['job_type'], name='jobs_job_typ_e7f4d4_idx')],
            },
        ),
    ]
