# Generated by Django 6.0.5 on 2026-05-08 13:02

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company_logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='company_logo'),
        ),
        migrations.AddField(
            model_name='job',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='job',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL (if not using Cloudinary)'),
        ),
    ]
