# Generated by Django 6.0.5 on 2026-05-08 13:08

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_company_logo_job_image_job_image_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.PositiveIntegerField(help_text='ID from main Application model')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('viewed', 'Viewed'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'job_applications_tracking',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='FontAwesome icon class', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Job Category',
                'verbose_name_plural': 'Job Categories',
                'db_table': 'job_categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Personal notes about this job')),
            ],
            options={
                'verbose_name': 'Saved Job',
                'verbose_name_plural': 'Saved Jobs',
                'db_table': 'saved_jobs',
                'ordering': ['-saved_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-created_at'], 'verbose_name': 'Job', 'verbose_name_plural': 'Jobs'},
        ),
        migrations.RemoveIndex(
            model_name='job',
            name='jobs_job_typ_e7f4d4_idx',
        ),
        migrations.AddField(
            model_name='job',
            name='application_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='When job posting expires', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, help_text='Featured jobs appear on homepage'),
        ),
        migrations.AddField(
            model_name='job',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='When job was first published', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='view_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='company_logo',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Company logo image', max_length=255, null=True, verbose_name='company_logo'),
        ),
        migrations.AlterField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience_level',
            field=models.CharField(choices=[('entry', 'Entry Level (0-2 years)'), ('intermediate', 'Intermediate (2-5 years)'), ('senior', 'Senior (5-8 years)'), ('expert', 'Expert (8+ years)')], db_index=True, default='intermediate', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload job advertisement image', max_length=255, null=True, verbose_name='job_image'),
        ),
        migrations.AlterField(
            model_name='job',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL (if not using Cloudinary upload)'),
        ),
        migrations.AlterField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('freelance', 'Freelance'), ('fulltime', 'Full Time'), ('parttime', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship')], db_index=True, default='freelance', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(db_index=True, default='Remote', max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='project_brief',
            field=models.TextField(help_text='The project applicant must complete before interview', verbose_name='Project Brief (Required for Interview)'),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_range',
            field=models.CharField(help_text='e.g., $80 - $100 per hour or $120k - $150k per year', max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='skills_required',
            field=models.JSONField(blank=True, default=list, help_text='List of required skills'),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['job_type', '-created_at'], name='jobs_job_typ_96e4cb_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['company', '-created_at'], name='jobs_company_2e21c5_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['location', '-created_at'], name='jobs_locatio_d069ea_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['is_featured', '-created_at'], name='jobs_is_feat_640174_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['expires_at'], name='jobs_expires_503a37_idx'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_applications', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='savedjob',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='savedjob',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['job', 'status'], name='job_applica_job_id_e30105_idx'),
        ),
        migrations.AddIndex(
            model_name='savedjob',
            index=models.Index(fields=['user', '-saved_at'], name='saved_jobs_user_id_e21ea0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='savedjob',
            unique_together={('user', 'job')},
        ),
    ]
