# Generated by Django 6.0.5 on 2026-05-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobapplication_jobcategory_savedjob_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='jobapplication',
            name='job_applica_job_id_e30105_idx',
        ),
        migrations.AddField(
            model_name='job',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='jobs.jobcategory'),
        ),
        migrations.DeleteModel(
            name='JobApplication',
        ),
    ]
