# Generated by Django 6.0.5 on 2026-05-11 15:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_remove_jobapplication_job_applica_job_id_e30105_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='application_deadline',
            field=models.DateTimeField(blank=True, help_text='Deadline for submitting applications. Applicants cannot apply after this date.', null=True),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['application_deadline'], name='jobs_applica_13933b_idx'),
        ),
    ]
