# Generated by Django 6.0.5 on 2026-05-09 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizquestion',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Quiz Question', 'verbose_name_plural': 'Quiz Questions'},
        ),
        migrations.AlterModelOptions(
            name='quizresult',
            options={'ordering': ['-completed_at'], 'verbose_name': 'Quiz Result', 'verbose_name_plural': 'Quiz Results'},
        ),
        migrations.RenameField(
            model_name='quizquestion',
            old_name='order_index',
            new_name='order',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='time_limit_seconds',
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='points',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False'), ('text', 'Text Answer')], default='multiple_choice', max_length=20),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='correct_answer',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='option_a',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='option_b',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='option_c',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='option_d',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='answers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='max_score',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='quizquestion',
            table=None,
        ),
        migrations.AlterModelTable(
            name='quizresult',
            table=None,
        ),
    ]
