# Generated by Django 6.0.5 on 2026-05-08 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpaymentmethod',
            old_name='bank_name',
            new_name='card_holder_name',
        ),
        migrations.RemoveField(
            model_name='userpaymentmethod',
            name='bank_account_name',
        ),
        migrations.RemoveField(
            model_name='userpaymentmethod',
            name='bank_account_number',
        ),
        migrations.RemoveField(
            model_name='userpaymentmethod',
            name='bank_swift_code',
        ),
        migrations.RemoveField(
            model_name='userpaymentmethod',
            name='binance_wallet',
        ),
        migrations.RemoveField(
            model_name='userpaymentmethod',
            name='method_type',
        ),
        migrations.RemoveField(
            model_name='userpaymentmethod',
            name='mpesa_phone',
        ),
        migrations.RemoveField(
            model_name='userpaymentmethod',
            name='okx_wallet',
        ),
        migrations.RemoveField(
            model_name='userpaymentmethod',
            name='paypal_email',
        ),
        migrations.AddField(
            model_name='userpaymentmethod',
            name='account_email',
            field=models.EmailField(blank=True, help_text='PayPal email or account email', max_length=254),
        ),
        migrations.AddField(
            model_name='userpaymentmethod',
            name='expiry_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userpaymentmethod',
            name='expiry_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userpaymentmethod',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userpaymentmethod',
            name='last_four',
            field=models.CharField(blank=True, help_text='Last 4 digits of card/account', max_length=4),
        ),
        migrations.AddField(
            model_name='userpaymentmethod',
            name='payment_type',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('paypal', 'PayPal'), ('bank_account', 'Bank Account'), ('mpesa', 'M-Pesa')], default=1039, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpaymentmethod',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number for M-Pesa', max_length=20),
        ),
        migrations.AddField(
            model_name='userpaymentmethod',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='userpaymentmethod',
            table=None,
        ),
    ]
