# Generated by Django 6.0.5 on 2026-05-08 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_options_user_country_user_created_at_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpaymentmethod',
            options={'ordering': ['-is_default', '-created_at']},
        ),
        migrations.AddField(
            model_name='user',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userpaymentmethod',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userpaymentmethod',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userpaymentmethod',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userpaymentmethod',
            name='bank_swift_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='userpaymentmethod',
            name='wallet_address',
            field=models.CharField(blank=True, help_text='Crypto wallet address', max_length=255),
        ),
        migrations.AlterField(
            model_name='userpaymentmethod',
            name='last_four',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='userpaymentmethod',
            name='payment_type',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('paypal', 'PayPal'), ('bank_account', 'Bank Account'), ('mpesa', 'M-Pesa'), ('binance', 'Binance Pay'), ('okx', 'OKX Pay')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['has_active_subscription'], name='accounts_us_has_act_4397db_idx'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='accounts_user',
        ),
        migrations.AlterModelTable(
            name='userpaymentmethod',
            table='accounts_user_payment_method',
        ),
    ]
