# Generated by Django 6.0.5 on 2026-05-08 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved - Take Quiz'), ('quiz_completed', 'Quiz Completed'), ('interview_scheduled', 'Interview Scheduled'), ('hired', 'Hired - Pending Onboarding'), ('onboarded', 'Onboarded - Active Freelancer'), ('rejected', 'Rejected')], default='pending', max_length=30)),
                ('cover_letter', models.TextField(blank=True)),
                ('quiz_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('quiz_completed_at', models.DateTimeField(blank=True, null=True)),
                ('interview_date', models.DateTimeField(blank=True, null=True)),
                ('interview_zoom_link', models.TextField(blank=True)),
                ('onboarding_date', models.DateTimeField(blank=True, null=True)),
                ('onboarding_zoom_link', models.TextField(blank=True)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('is_active_employment', models.BooleanField(default=False)),
                ('hired_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'applications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='application_user_id_4cfcce_idx'), models.Index(fields=['job', 'status'], name='application_job_id_606b4d_idx')],
                'unique_together': {('user', 'job')},
            },
        ),
    ]
