# Generated by Django 6.0.5 on 2026-05-09 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='application',
            name='application_user_id_4cfcce_idx',
        ),
        migrations.RemoveIndex(
            model_name='application',
            name='application_job_id_606b4d_idx',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='quiz_completed_at',
            new_name='quiz_expires_at',
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='application',
            name='additional_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='application',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='application',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='notice_period',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='application',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='portfolio_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='quiz_duration_minutes',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='application',
            name='quiz_taken_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='application',
            name='years_experience',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='interview_zoom_link',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='application',
            name='onboarding_zoom_link',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='application',
            name='quiz_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('interview_scheduled', 'Interview Scheduled'), ('hired', 'Hired'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterModelTable(
            name='application',
            table=None,
        ),
        migrations.RemoveField(
            model_name='application',
            name='onboarding_completed',
        ),
    ]
