# Generated by Django 6.0.5 on 2026-05-09 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_remove_application_application_user_id_4cfcce_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='is_active_employment',
            new_name='interview_completed',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='interview_date',
            new_name='interview_scheduled_at',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='onboarding_date',
            new_name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='application',
            name='additional_notes',
        ),
        migrations.RemoveField(
            model_name='application',
            name='email',
        ),
        migrations.RemoveField(
            model_name='application',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='interview_zoom_link',
        ),
        migrations.RemoveField(
            model_name='application',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='application',
            name='notice_period',
        ),
        migrations.RemoveField(
            model_name='application',
            name='onboarding_zoom_link',
        ),
        migrations.RemoveField(
            model_name='application',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='application',
            name='portfolio_url',
        ),
        migrations.RemoveField(
            model_name='application',
            name='quiz_duration_minutes',
        ),
        migrations.RemoveField(
            model_name='application',
            name='quiz_expires_at',
        ),
        migrations.RemoveField(
            model_name='application',
            name='quiz_score',
        ),
        migrations.RemoveField(
            model_name='application',
            name='quiz_taken_at',
        ),
        migrations.RemoveField(
            model_name='application',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='application',
            name='years_experience',
        ),
        migrations.AddField(
            model_name='application',
            name='deployment_link',
            field=models.URLField(blank=True, help_text='Live demo link (optional)', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='feedback',
            field=models.TextField(blank=True, help_text='Feedback for rejected applications', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='interview_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='project_file',
            field=models.FileField(blank=True, null=True, upload_to='applications/projects/'),
        ),
        migrations.AddField(
            model_name='application',
            name='project_notes',
            field=models.TextField(blank=True, help_text='Additional notes about the project', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='repository_link',
            field=models.URLField(default=223, help_text='GitHub/GitLab repository link'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='start_date',
            field=models.DateField(blank=True, help_text='Job start date', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='test_credentials',
            field=models.TextField(blank=True, help_text='Test credentials for the deployed site', null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='cover_letter',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('shortlisted', 'Shortlisted - Under Review'), ('approved', 'Approved for Interview'), ('interview_scheduled', 'Interview Scheduled'), ('interview_completed', 'Interview Completed'), ('hired', 'Hired'), ('rejected', 'Rejected')], default='pending', max_length=30),
        ),
    ]
