# Generated by Django 6.0.5 on 2026-05-08 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoomMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_type', models.CharField(choices=[('interview', 'Interview (60 min)'), ('onboarding', 'Onboarding (45 min)')], max_length=20)),
                ('meeting_id', models.CharField(max_length=100, unique=True)),
                ('join_url', models.URLField(max_length=500)),
                ('start_url', models.URLField(blank=True, max_length=500)),
                ('password', models.CharField(blank=True, max_length=50)),
                ('start_time', models.DateTimeField()),
                ('duration_minutes', models.IntegerField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('started', 'Started'), ('ended', 'Ended'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zoom_meetings', to='application.application')),
            ],
            options={
                'db_table': 'zoom_meetings',
                'ordering': ['-start_time'],
            },
        ),
    ]
