# Generated by Django 6.0.5 on 2026-05-09 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_rename_is_active_employment_application_interview_completed_and_more'),
        ('zoom_integration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zoommeeting',
            name='meeting_type',
        ),
        migrations.RemoveField(
            model_name='zoommeeting',
            name='password',
        ),
        migrations.RemoveField(
            model_name='zoommeeting',
            name='status',
        ),
        migrations.RemoveField(
            model_name='zoommeeting',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='zoommeeting',
            name='topic',
            field=models.CharField(default=234, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zoommeeting',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zoom_meetings', to='application.application'),
        ),
        migrations.AlterField(
            model_name='zoommeeting',
            name='duration_minutes',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='zoommeeting',
            name='join_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='zoommeeting',
            name='start_url',
            field=models.URLField(),
        ),
        migrations.AlterModelTable(
            name='zoommeeting',
            table=None,
        ),
    ]
