# Generated by Django 6.0.5 on 2026-05-11 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_rename_is_active_employment_application_interview_completed_and_more'),
        ('zoom_integration', '0002_remove_zoommeeting_meeting_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zoommeeting',
            options={'ordering': ['start_time']},
        ),
        migrations.RemoveField(
            model_name='zoommeeting',
            name='start_url',
        ),
        migrations.AddField(
            model_name='zoommeeting',
            name='meeting_type',
            field=models.CharField(choices=[('interview', 'Interview'), ('onboarding', 'Onboarding')], default='interview', max_length=20),
        ),
        migrations.AddField(
            model_name='zoommeeting',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20),
        ),
        migrations.AddField(
            model_name='zoommeeting',
            name='user',
            field=models.ForeignKey(default=929, on_delete=django.db.models.deletion.CASCADE, related_name='zoom_meetings', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zoommeeting',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zoom_meetings', to='application.application'),
        ),
        migrations.AlterField(
            model_name='zoommeeting',
            name='join_url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='zoommeeting',
            name='meeting_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='zoommeeting',
            name='topic',
            field=models.CharField(max_length=255),
        ),
    ]
