# Generated by Django 6.0.5 on 2026-05-11 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoom_integration', '0003_alter_zoommeeting_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoommeeting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
