# Generated by Django 6.0.5 on 2026-05-11 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoom_integration', '0004_zoommeeting_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zoommeeting',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('postponed', 'Postponed')], default='scheduled', max_length=20),
        ),
    ]
