# Generated by Django 6.0.5 on 2026-05-11 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoom_integration', '0005_alter_zoommeeting_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoommeeting',
            name='postpone_reason',
            field=models.TextField(blank=True, help_text='Reason for postponement', null=True),
        ),
        migrations.AddField(
            model_name='zoommeeting',
            name='rescheduled_date',
            field=models.DateTimeField(blank=True, help_text='New date for rescheduled meeting', null=True),
        ),
    ]
