# Generated by Django 6.0.5 on 2026-05-08 12:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_email', models.EmailField(default='support@radiloxremotejobs.com', max_length=254)),
                ('sales_email', models.EmailField(default='sales@radiloxremotejobs.com', max_length=254)),
                ('careers_email', models.EmailField(default='careers@radiloxremotejobs.com', max_length=254)),
                ('email_response_time', models.CharField(default='Within 24 hours', help_text='e.g., Within 24 hours', max_length=100)),
                ('phone_number', models.CharField(default='+1 (555) 123-4567', max_length=50)),
                ('phone_hours', models.CharField(default='Mon-Fri, 9am-6pm EST', help_text='Phone availability hours', max_length=200)),
                ('chat_enabled', models.BooleanField(default=True)),
                ('chat_message', models.CharField(default='Available on the platform', help_text='Chat availability message', max_length=200)),
                ('chat_instruction', models.CharField(default='Click the chat icon at the bottom right', help_text='Chat instruction text', max_length=200)),
                ('monday_friday_hours', models.CharField(default='9:00 AM - 6:00 PM EST', max_length=100)),
                ('saturday_hours', models.CharField(default='10:00 AM - 2:00 PM EST', max_length=100)),
                ('sunday_hours', models.CharField(default='Closed', max_length=100)),
                ('address', models.TextField(blank=True, help_text='Physical address')),
                ('map_embed_url', models.URLField(blank=True, help_text='Google Maps embed URL')),
                ('faq_section_title', models.CharField(default='Frequently asked questions', max_length=200)),
                ('faq_section_subtitle', models.CharField(default='Find quick answers to common questions', max_length=200)),
                ('faq_button_text', models.CharField(default='View all FAQs', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Information',
                'verbose_name_plural': 'Contact Information',
                'db_table': 'contact_info',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('category', models.CharField(default='general', help_text='e.g., general, payments, technical', max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'db_table': 'faqs',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('twitter', 'Twitter/X'), ('linkedin', 'LinkedIn'), ('github', 'GitHub'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('discord', 'Discord'), ('slack', 'Slack')], max_length=50)),
                ('url', models.URLField(validators=[django.core.validators.URLValidator()])),
                ('icon_class', models.CharField(blank=True, help_text='Optional: Custom icon class', max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Social Link',
                'verbose_name_plural': 'Social Links',
                'db_table': 'social_links',
                'ordering': ['order', 'platform'],
            },
        ),
    ]
