# Generated by Django 6.0.5 on 2026-05-08 13:12

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contactinfo_faq_sociallink'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Newsletter Subscriber',
                'verbose_name_plural': 'Newsletter Subscribers',
                'db_table': 'newsletter_subscribers',
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='RadiloxRemoteJobs', max_length=100)),
                ('site_tagline', models.CharField(default='Remote IT Talent Platform', max_length=200)),
                ('site_logo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='logo')),
                ('site_favicon', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='favicon')),
                ('meta_description', models.TextField(blank=True, help_text='Default meta description')),
                ('meta_keywords', models.CharField(blank=True, help_text='Default meta keywords', max_length=500)),
                ('google_analytics_id', models.CharField(blank=True, max_length=50)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('maintenance_message', models.TextField(blank=True)),
                ('contact_email', models.EmailField(default='contact@radiloxremotejobs.com', max_length=254)),
                ('admin_email', models.EmailField(default='admin@radiloxremotejobs.com', max_length=254)),
                ('twitter_card_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='twitter_card')),
                ('facebook_og_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='facebook_og')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
                'db_table': 'site_settings',
            },
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Contact Message', 'verbose_name_plural': 'Contact Messages'},
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='chat_widget_code',
            field=models.TextField(blank=True, help_text='Embed code for chat widget'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='discord_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='github_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='legal_email',
            field=models.EmailField(default='legal@radiloxremotejobs.com', max_length=254),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='newsletter_button_text',
            field=models.CharField(default='Subscribe', max_length=100),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='newsletter_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='newsletter_subtitle',
            field=models.CharField(default='Get the latest updates and offers', max_length=200),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='newsletter_title',
            field=models.CharField(default='Subscribe to our newsletter', max_length=200),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='phone_emergency',
            field=models.CharField(blank=True, help_text='Emergency contact number', max_length=50),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='privacy_email',
            field=models.EmailField(default='privacy@radiloxremotejobs.com', max_length=254),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='tiktok_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='trust_badges',
            field=models.JSONField(blank=True, default=list, help_text='List of trust badges/certifications'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='twitter_handle',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_info_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='youtube_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='responded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='response_message',
            field=models.TextField(blank=True, help_text="Admin's response message"),
        ),
        migrations.AddField(
            model_name='faq',
            name='helpful_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='faq',
            name='not_helpful_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='faq',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='show_in_contact',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='show_in_footer',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('new', '🔴 New'), ('read', '🟡 Read'), ('replied', '🟢 Replied'), ('archived', '⚪ Archived'), ('spam', '⚠️ Spam')], db_index=True, default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(choices=[('general', 'General Inquiry'), ('hiring', 'Hiring / Post a Job'), ('freelancer', 'Becoming a Freelancer'), ('payment', 'Payment Issue'), ('technical', 'Technical Support'), ('partnership', 'Partnership Opportunity'), ('bug', 'Bug Report'), ('feature', 'Feature Request'), ('complaint', 'Complaint'), ('other', 'Other')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='faq',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('for_freelancers', 'For Freelancers'), ('for_employers', 'For Employers'), ('payments', 'Payments & Withdrawals'), ('technical', 'Technical Support'), ('account', 'Account & Security'), ('billing', 'Billing & Subscriptions'), ('jobs', 'Jobs & Applications'), ('tasks', 'Tasks & Projects')], db_index=True, default='general', max_length=50),
        ),
        migrations.AlterField(
            model_name='faq',
            name='order',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='order',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='platform',
            field=models.CharField(choices=[('twitter', 'Twitter/X'), ('linkedin', 'LinkedIn'), ('github', 'GitHub'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('discord', 'Discord'), ('slack', 'Slack'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('medium', 'Medium'), ('devto', 'Dev.to'), ('stackoverflow', 'Stack Overflow')], db_index=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['subject'], name='contact_mes_subject_e995b6_idx'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['created_at'], name='contact_mes_created_eb3e69_idx'),
        ),
        migrations.AddIndex(
            model_name='faq',
            index=models.Index(fields=['category', 'is_active'], name='faqs_categor_839aa4_idx'),
        ),
        migrations.AddIndex(
            model_name='faq',
            index=models.Index(fields=['order'], name='faqs_order_d2a62f_idx'),
        ),
        migrations.AddIndex(
            model_name='newslettersubscriber',
            index=models.Index(fields=['email'], name='newsletter__email_9c0aba_idx'),
        ),
        migrations.AddIndex(
            model_name='newslettersubscriber',
            index=models.Index(fields=['is_active'], name='newsletter__is_acti_3f96c7_idx'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_settings_updates', to=settings.AUTH_USER_MODEL),
        ),
    ]
