# Generated by Django 6.0.5 on 2026-05-10 14:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='crypto_tx_hash',
        ),
        migrations.AddField(
            model_name='userwallet',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reference_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('task_payment', 'Task Payment'), ('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('refund', 'Refund')], max_length=20),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='admin_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='destination_details',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='payment_method',
            field=models.CharField(choices=[('paypal', 'PayPal'), ('mpesa', 'M-Pesa'), ('bank_account', 'Bank Account'), ('crypto', 'Cryptocurrency')], max_length=20),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='requested_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
