# Generated by Django 6.0.5 on 2026-05-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(blank=True, help_text='Task preview image', null=True, upload_to='task_images/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='task',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL for task preview', null=True),
        ),
    ]
