# Generated by Django 6.0.5 on 2026-05-11 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionpayment',
            old_name='amount_usd',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='subscriptionpayment',
            name='expires_at',
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='payment_method',
            field=models.CharField(choices=[('binance', 'Binance Pay'), ('okx', 'OKX Pay'), ('paypal', 'PayPal'), ('mpesa', 'M-Pesa'), ('bank', 'Bank Transfer'), ('crypto', 'Cryptocurrency')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('pending_verification', 'Pending Verification')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='free', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subscriptions',
                'ordering': ['-created_at'],
            },
        ),
    ]
