# Generated by Django 6.0.5 on 2026-05-08 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_on_application', models.BooleanField(default=True)),
                ('email_on_quiz', models.BooleanField(default=True)),
                ('email_on_task', models.BooleanField(default=True)),
                ('email_on_payment', models.BooleanField(default=True)),
                ('email_on_subscription', models.BooleanField(default=True)),
                ('email_on_interview', models.BooleanField(default=True)),
                ('email_on_withdrawal', models.BooleanField(default=True)),
                ('in_app_on_application', models.BooleanField(default=True)),
                ('in_app_on_quiz', models.BooleanField(default=True)),
                ('in_app_on_task', models.BooleanField(default=True)),
                ('in_app_on_payment', models.BooleanField(default=True)),
                ('in_app_on_subscription', models.BooleanField(default=True)),
                ('in_app_on_interview', models.BooleanField(default=True)),
                ('in_app_on_withdrawal', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
                'db_table': 'notification_preferences',
            },
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='is_read',
        ),
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('unread', 'Unread'), ('read', 'Read'), ('archived', 'Archived')], db_index=True, default='unread', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, help_text='URL to redirect when clicked', max_length=500),
        ),
        migrations.AlterField(
            model_name='notification',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional data like task_id, application_id, etc.'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('application', 'Application Update'), ('quiz', 'Quiz Result'), ('task', 'Task Update'), ('payment', 'Payment Update'), ('subscription', 'Subscription Update'), ('system', 'System Message'), ('interview', 'Interview Scheduled'), ('onboarding', 'Onboarding Scheduled'), ('withdrawal', 'Withdrawal Update')], db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'status', '-created_at'], name='notificatio_user_id_a34568_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'created_at'], name='notificatio_user_id_7336fd_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='notificatio_notific_19df93_idx'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL),
        ),
    ]
